import './globals.css'
import { Inter } from 'next/font/google'
import { TopNav } from '@/components/TopNav/TopNav';
import { Banner } from '@/components/Banner/Banner';
import { Filler } from '@/components/Filler/Filler';
import { BannerTwo } from '@/components/BannerTwo/BannerTwo';
import { BannerThree } from '@/components/BannerThree/BannerThree';
import { Carousel } from '@/components/Carousel/Carousel';
import { Privacy } from '@/components/Privacy/Privacy';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <TopNav />
            <Banner />
            <Filler />
            <Carousel />
            <BannerTwo />
            <Filler />
            <BannerThree />
            <Privacy />
        {children}
      </body>
    </html>
  )
}
